Support/improvments 01 (#3047)
* Op recreate is requested when op is deleted

Signed-off-by: Martin Vala <mavala@redhat.com>

* Fix problem with path detection

Signed-off-by: Martin Vala <mavala@redhat.com>

* Improved check for latest version

Signed-off-by: Martin Vala <mavala@redhat.com>

* Cosmetics

Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/actions-env b/scripts/ci/actions-env
--- a/scripts/ci/actions-env
+++ b/scripts/ci/actions-env
@@ -41,31 +41,26 @@ if [ -n "$OP_TEST_REMOVED_FILES" ];then
 
   # Some files are removed
   # TODO : OP_TEST_CHNAGES_OPERATOR_VERSIONS_REMOVED
-
+  FILES=
+  for sf in ${OP_TEST_REMOVED_FILES}; do
+    echo $sf
+    # Check if .github/ dir is modified
+    [[ $sf == .github* ]] && OP_TEST_CHNAGES_GITHUB=1 && continue
+    [[ $sf == scripts* ]] && OP_TEST_CHNAGES_CI=1 && continue
+    [[ $sf == docs* ]] && OP_TEST_CHNAGES_DOCS=1 && continue
+    [[ $sf == community-operators* ]] && OP_TEST_CHNAGES_STREAM_COMMUNITY=1
+    [[ $sf == upstream-community-operators* ]] && OP_TEST_CHNAGES_STREAM_UPSTREAM=1
+    [[ $sf == *package.yaml ]] && continue
+    [[ $sf == *ci.yaml ]] && { OP_TEST_CHNAGES_CI_YAML=1; continue; }
+    [[ $OP_TEST_CHNAGES_STREAM_COMMUNITY -eq 0 ]] && [[ $OP_TEST_CHNAGES_STREAM_UPSTREAM -eq 0 ]] && { echo "No changes 'community-operators' or 'upstream-community-operators' !!! Exiting ..."; OP_RELEASE_READY=0; }
+    FILES="$FILES $(echo $sf | cut -d '/' -f 1-3)"
+    # Check if outdside of "community-operators" and "upstream-community-operators"
+  done
   # Handle removed only files
   if [ ! -n "$OP_TEST_MODIFIED_FILES" ];then
     # check if only ci.yaml was removed
     OP_RELEASE_READY=1
-    FILES=
-    for sf in ${OP_TEST_REMOVED_FILES}; do
-      echo $sf
-      # Check if .github/ dir is modified
-      [[ $sf == .github* ]] && OP_TEST_CHNAGES_GITHUB=1 && continue
-      [[ $sf == scripts* ]] && OP_TEST_CHNAGES_CI=1 && continue
-      [[ $sf == docs* ]] && OP_TEST_CHNAGES_DOCS=1 && continue
 
-      [[ $sf == community-operators* ]] && OP_TEST_CHNAGES_STREAM_COMMUNITY=1
-      [[ $sf == upstream-community-operators* ]] && OP_TEST_CHNAGES_STREAM_UPSTREAM=1
-
-      [[ $sf == *package.yaml ]] && continue
-      [[ $sf == *ci.yaml ]] && { OP_TEST_CHNAGES_CI_YAML=1; continue; }
-
-      [[ $OP_TEST_CHNAGES_STREAM_COMMUNITY -eq 0 ]] && [[ $OP_TEST_CHNAGES_STREAM_UPSTREAM -eq 0 ]] && { echo "No changes 'community-operators' or 'upstream-community-operators' !!! Exiting ..."; OP_RELEASE_READY=0; }
-
-      FILES="$FILES $(echo $sf | cut -d '/' -f 1-3)"
-
-      # Check if outdside of "community-operators" and "upstream-community-operators"
-    done
 
     [[ $OP_TEST_CHNAGES_STREAM_COMMUNITY -eq 1 ]] && OP_TEST_STREAM_NAME="community-operators"
     [[ $OP_TEST_CHNAGES_STREAM_UPSTREAM -eq 1 ]] && OP_TEST_STREAM_NAME="upstream-community-operators"
@@ -102,12 +97,13 @@ if [ -n "$OP_TEST_REMOVED_FILES" ];then
       for f in $(find ${OP_TEST_STREAM_NAME}/${OP_TEST_OPERATOR_NAME} -type f);do
         OP_TEST_MODIFIED_FILES="$OP_TEST_MODIFIED_FILES $f"
       done
-
       echo "Final modified files are :"
       echo "$OP_TEST_MODIFIED_FILES"
-
     fi
 
+  else
+    REMOVED_VERSIONS=$(echo -e "${FILES// /\\n}" | uniq | sort -r)
+    FILES=
   fi
 fi
 
@@ -156,9 +152,12 @@ fi
 echo "FILES: $FILES"
 
 VERSIONS=$(echo -e "${FILES// /\\n}" | uniq | sort -r)
+
 LATEST="$(echo -e $VERSIONS | cut -d ' ' -f 1)"
 OP_TEST_OPERATOR_NAME=$(echo $LATEST | cut -d '/' -f 2)
 OP_TEST_OPERATOR_VERSION=$(echo $LATEST | cut -d '/' -f 3)
+OP_TEST_OPERATOR_VERSIONS_ALL="$(find $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME -type f -name "*.clusterserviceversion.yaml" | sort --version-sort | cut -d '/' -f 3 | tr '\n' ' ')"
+OP_TEST_OPERATOR_VERSIONS_ALL_LATEST="$(find $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME -type f -name "*.clusterserviceversion.yaml" | sort --version-sort | tail -n 1 | cut -d '/' -f 3)"
 
 OP_TEST_OPERATOR_VERSIONS=
 for v in $VERSIONS;do
@@ -169,6 +168,13 @@ done
 # remove trailing space
 OP_TEST_OPERATOR_VERSIONS=$(echo $OP_TEST_OPERATOR_VERSIONS | sed 's/ *$//g')
 
+OP_TEST_OPERATOR_VERSIONS_REMOVED=
+for v in $REMOVED_VERSIONS;do
+  OP_TEST_OPERATOR_VERSIONS_REMOVED="$(echo $v| cut -d '/' -f 3) $OP_TEST_OPERATOR_VERSIONS_REMOVED"  
+done
+# remove trailing space
+OP_TEST_OPERATOR_VERSIONS_REMOVED=$(echo $OP_TEST_OPERATOR_VERSIONS_REMOVED | sed 's/ *$//g')
+
 [[ $OP_TEST_PROD -ge 1 ]] && OP_RELEASE_READY=1
 
 if [[ $OP_TEST_CI_YAML_ONLY -eq 1 ]];then
@@ -176,13 +182,18 @@ if [[ $OP_TEST_CI_YAML_ONLY -eq 1 ]];then
     OP_TEST_OPERATOR_VERSION="sync"
     OP_TEST_OPERATOR_VERSIONS="$OP_TEST_OPERATOR_VERSION"
   else
-    OP_TEST_OPERATOR_VERSION="$(find community-operators/aqua -type f -name "*.clusterserviceversion.yaml" | sort --version-sort | tail -n 1 | cut -d '/' -f 3)"
+    OP_TEST_OPERATOR_VERSION="$(find $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME -type f -name "*.clusterserviceversion.yaml" | sort --version-sort | tail -n 1 | cut -d '/' -f 3)"
     OP_TEST_OPERATOR_VERSIONS="$OP_TEST_OPERATOR_VERSION"
   fi
 fi
+[ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; exit 1;  }
 
 echo "Latest : $LATEST"
+echo "OP_TEST_OPERATOR_VERSION: $OP_TEST_OPERATOR_VERSION"
 echo "OP_TEST_OPERATOR_VERSIONS : $OP_TEST_OPERATOR_VERSIONS"
+echo "OP_TEST_OPERATOR_VERSIONS_ALL : $OP_TEST_OPERATOR_VERSIONS_ALL"
+echo "OP_TEST_OPERATOR_VERSIONS_ALL_LATEST : $OP_TEST_OPERATOR_VERSIONS_ALL_LATEST"
+echo "OP_TEST_OPERATOR_VERSIONS_REMOVED : $OP_TEST_OPERATOR_VERSIONS_REMOVED"
 echo "OP_TEST_CHNAGES_GITHUB=$OP_TEST_CHNAGES_GITHUB"
 echo "OP_TEST_CHNAGES_CI=$OP_TEST_CHNAGES_CI"
 echo "OP_TEST_CHNAGES_DOC=$OP_TEST_CHNAGES_DOCS"
