Removing updategraph feature tmp
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/actions-env b/scripts/ci/actions-env
--- a/scripts/ci/actions-env
+++ b/scripts/ci/actions-env
@@ -261,15 +261,15 @@ OP_TEST_OPERATOR_VERSIONS_ALL_COUNT=0
 
 [[ $OP_TEST_CI_YAML_MODIFIED -eq 1 ]] && [[ $OP_TEST_CI_YAML_ONLY -eq 0 ]] && { echo "We support only a single file modification in case of 'ci.yaml' file. If you want to update it, please make an extra PR with 'ci.yaml' file modification only !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/."; exit 1; }
 
-if [[ $OP_TEST_READY -eq 1 ]];then
-  [ ! -f $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml ] &&  { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' is present !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/. !!!"; exit 1; }
-  [ command -v yq &> /dev/null ] || { echo "Command 'yq' could not be found !!!"; exit 1; } 
-  TEST_REVIEWERS=$(cat $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml | yq '.revierers')
-  [[ $OP_TEST_READY -eq 1 ]] && [ $TEST_REVIEWERS == "null" ] &&  { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' contains 'reviewers' field !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/ !!!"; exit 1; }
+# if [[ $OP_TEST_READY -eq 1 ]];then
+#   [ ! -f $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml ] &&  { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' is present !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/. !!!"; exit 1; }
+#   # [ command -v yq &> /dev/null ] || { echo "Command 'yq' could not be found !!!"; exit 1; } 
+#   TEST_REVIEWERS=$(cat $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml | yq '.revierers')
+#   [[ $OP_TEST_READY -eq 1 ]] && [ $TEST_REVIEWERS == "null" ] &&  { echo "We require that file '$OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml' contains 'reviewers' field !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/ !!!"; exit 1; }
 
-  TEST_UPDATE_GRAPH=$(cat $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml | yq '.updateGraph')
-  [ $TEST_UPDATE_GRAPH == "null" ] && OP_TEST_UPDATEGRAPH=0
-fi
+#   TEST_UPDATE_GRAPH=$(cat $OP_TEST_STREAM_NAME/$OP_TEST_OPERATOR_NAME/ci.yaml | yq '.updateGraph')
+#   [ $TEST_UPDATE_GRAPH == "null" ] && OP_TEST_UPDATEGRAPH=0
+# fi
 
 OP_TEST_PR_TITLE="$OP_TEST_STREAM_NAME"
 [[ $OPRT -eq 1 ]] && [[ $OP_TEST_VER_OVERWRITE -eq 1 ]] && OP_TEST_PR_TITLE="$OP_TEST_PR_TITLE [O]"
