Recreate improvments
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/actions-env b/scripts/ci/actions-env
--- a/scripts/ci/actions-env
+++ b/scripts/ci/actions-env
@@ -268,17 +268,21 @@ if [[ $OP_TEST_CI_YAML_ONLY -eq 1 ]];then
 fi
 
 OP_TEST_OPERATOR_VERSIONS_COUNT=0
-
 [ -n "$OP_TEST_OPERATOR_VERSIONS" ] && OP_TEST_OPERATOR_VERSIONS_COUNT=$(echo $OP_TEST_OPERATOR_VERSIONS | tr ' ' '\n' | wc -l)
+OP_TEST_OPERATOR_VERSIONS_REMOVED_COUNT=0
+[ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && OP_TEST_OPERATOR_VERSIONS_REMOVED_COUNT=$(echo $OP_TEST_OPERATOR_VERSIONS_REMOVED | tr ' ' '\n' | wc -l)
+
 
 OP_TEST_OPERATOR_VERSIONS_ALL_COUNT=0
 [ -n "$OP_TEST_OPERATOR_VERSIONS_ALL" ] && OP_TEST_OPERATOR_VERSIONS_ALL_COUNT=$(echo $OP_TEST_OPERATOR_VERSIONS_ALL | tr ' ' '\n' | wc -l)
 
-[[ $OPRT -eq 1 ]] && [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "::set-output name=op_test_error_code::6"; exit 1;  }
+echo "Versions Count: CHANGED[$OP_TEST_OPERATOR_VERSIONS] REMOVED[$OP_TEST_OPERATOR_VERSIONS_REMOVED]"
+
+# [[ $OPRT -eq 1 ]] && [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "::set-output name=op_test_error_code::6"; exit 1;  }
 
 [[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -eq 1 ]] && [[ $OP_TEST_IS_MODIFIED -eq 1 ]] && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=1
-[[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -eq 1 ]] && [[ $OP_TEST_IS_MODIFIED -eq 1 ]] && [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=1 && OP_TEST_VER_OVERWRITE=1 && OP_TEST_RECREATE=0
-[[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -gt 1 ]] && OP_TEST_SET_LABEL_OPERATOR_RECREATE=1 && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=0 && OP_TEST_VER_OVERWRITE=1 && OP_TEST_RECREATE=0
+[[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -eq 1 ]] && [[ $OP_TEST_IS_MODIFIED -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_REMOVED_COUNT -gt 0 ]] && OP_TEST_SET_LABEL_OPERATOR_RECREATE=1 && OP_TEST_RECREATE=1 && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=0 && OP_TEST_VER_OVERWRITE=0
+[[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -gt 1 ]] && OP_TEST_SET_LABEL_OPERATOR_RECREATE=1 && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=0 && OP_TEST_VER_OVERWRITE=0 && OP_TEST_RECREATE=1
 [[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_ALL_COUNT -eq 1 ]] && OP_TEST_IS_NEW_OPERATOR=1 && OP_TEST_RECREATE=1 && OP_TEST_SET_LABEL_OPERATOR_RECREATE=1 && OP_TEST_VER_OVERWRITE=0 && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=0
 
 # [[ $OPRT -eq 0 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -gt 1 ]] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && { echo "Error: Multiple versions [$OP_TEST_OPERATOR_VERSIONS] were modified and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "::set-output name=op_test_error_code::5"; exit 1;  }
