Fix (#3132)
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/actions-env b/scripts/ci/actions-env
--- a/scripts/ci/actions-env
+++ b/scripts/ci/actions-env
@@ -194,7 +194,12 @@ if [[ $OP_TEST_CI_YAML_ONLY -eq 1 ]];then
     OP_TEST_OPERATOR_VERSIONS="$OP_TEST_OPERATOR_VERSION"
   fi
 fi
+
+OP_TEST_OPERATOR_VERSIONS_COUNT=$(echo $OP_TEST_OPERATOR_VERSIONS | tr ' ' '\n' | wc -l)
+
 [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; exit 1;  }
+
+[[ $OP_TEST_OPERATOR_VERSIONS_COUNT -gt 1 ]] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && { echo "Error: Multiple versions [$OP_TEST_OPERATOR_VERSIONS] were modified and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; exit 1;  }
 
 echo "Latest : $LATEST"
 echo "OP_TEST_OPERATOR_VERSION: $OP_TEST_OPERATOR_VERSION"
