Improvments in versions removed
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/actions-env b/scripts/ci/actions-env
--- a/scripts/ci/actions-env
+++ b/scripts/ci/actions-env
@@ -274,10 +274,7 @@ OP_TEST_OPERATOR_VERSIONS_COUNT=0
 OP_TEST_OPERATOR_VERSIONS_ALL_COUNT=0
 [ -n "$OP_TEST_OPERATOR_VERSIONS_ALL" ] && OP_TEST_OPERATOR_VERSIONS_ALL_COUNT=$(echo $OP_TEST_OPERATOR_VERSIONS_ALL | tr ' ' '\n' | wc -l)
 
-[ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "::set-output name=op_test_error_code::6"; exit 1;  }
-
-# echo "::set-output name=op_test_set_label_operator_version_overwrite::0"
-# echo "::set-output name=op_test_set_label_operator_recreate::0"
+[[ $OPRT -eq 1 ]] && [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && [[ ! $OP_TEST_RECREATE -eq 1 ]] && [ "$OP_TEST_OPERATOR_VERSIONS_REMOVED" != "$OP_TEST_OPERATOR_VERSIONS_ALL_LATEST" ] && { echo "Error: Old versions [$OP_TEST_OPERATOR_VERSIONS_REMOVED] were removed and 'allow/operator-recreate' is NOT set !!! Please set it first !!! Exiting ..."; echo "::set-output name=op_test_error_code::6"; exit 1;  }
 
 [[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -eq 1 ]] && [[ $OP_TEST_IS_MODIFIED -eq 1 ]] && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=1
 [[ $OPRT -eq 1 ]] && [[ $OP_TEST_OPERATOR_VERSIONS_COUNT -eq 1 ]] && [[ $OP_TEST_IS_MODIFIED -eq 1 ]] && [ -n "$OP_TEST_OPERATOR_VERSIONS_REMOVED" ] && OP_TEST_SET_LABEL_OPERATOR_VERSION_OVERWRITE=1 && OP_TEST_VER_OVERWRITE=1 && OP_TEST_RECREATE=0
@@ -289,7 +286,7 @@ OP_TEST_OPERATOR_VERSIONS_ALL_COUNT=0
 
 [[ $OP_TEST_VER_OVERWRITE -eq 1 ]] && [[ $OP_TEST_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' is set. Only one label can be set !!! Exiting ..."; echo "::set-output name=op_test_error_code::1"; exit 1; }
 
-[[ $OP_TEST_CI_YAML_MODIFIED -eq 1 ]] && [[ $OP_TEST_CI_YAML_ONLY -eq 0 ]] && { echo "We support only a single file modification in case of 'ci.yaml' file. If you want to update it, please make an extra PR with 'ci.yaml' file modification only !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/."; echo "::set-output name=op_test_error_code::7"; exit 1; }
+[[ $OPRT -eq 1 ]] && [[ $OP_TEST_CI_YAML_MODIFIED -eq 1 ]] && [[ $OP_TEST_CI_YAML_ONLY -eq 0 ]] && { echo "We support only a single file modification in case of 'ci.yaml' file. If you want to update it, please make an extra PR with 'ci.yaml' file modification only !!! More info : https://operator-framework.github.io/community-operators/operator-ci-yaml/."; echo "::set-output name=op_test_error_code::7"; exit 1; }
 
 echo "::set-output name=op_test_stream::${OP_TEST_STREAM_NAME}"
 echo "::set-output name=op_test_name::${OP_TEST_OPERATOR_NAME}"
