Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/ansible-env b/scripts/ci/ansible-env
--- a/scripts/ci/ansible-env
+++ b/scripts/ci/ansible-env
@@ -101,9 +101,9 @@ if [ -z "${OP_PATH+xxx}" ]; then
 #  exit 1
 fi
 
-[[ $OP_VER_OVERWRITE -eq 1 ]] && [[ $OP_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' cannot be set simultaneously !!!"; exit 1; }
+# [[ $OP_VER_OVERWRITE -eq 1 ]] && [[ $OP_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' cannot be set simultaneously !!!"; exit 1; }
 
-cat <<EOF >$INPUT_ENV_SCRIPT
+cat <<EOF > $INPUT_ENV_SCRIPT
 export OP_PATH=$OP_PATH
 export OP_NAME=$OP_NAME
 export OP_VER=$OP_VER
