revert removed by merge

diff --git a/scripts/ci/check-kubeconfig b/scripts/ci/check-kubeconfig
--- a/scripts/ci/check-kubeconfig
+++ b/scripts/ci/check-kubeconfig
@@ -4,11 +4,14 @@ for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
   . "$f"
 done
 
+if [ -z "${KUBECONFIG}" ]; then
+    export KUBECONFIG=~/.kube/config
+fi
 export_color
+
 CONTEXT="$(kubectl config view -o jsonpath='{.current-context}')"
 
 if [[ -f $KUBECONFIG && "${CONTEXT}" != ""  ]]; then
-    READY=1
 
     IP="$(kubectl config view -o jsonpath="{.clusters[?(@.name=='$CONTEXT')].cluster.server}")"
     echo ${IP#*//} | sed -e "s/:/ /" | while read ip port
@@ -17,7 +20,7 @@ if [[ -f $KUBECONFIG && "${CONTEXT}" != ""  ]]; then
         set -e
         nc -zvw3 $ip $port 2> /dev/null
       } || {
-        printf "Kube api not listening on $ip:$port %s[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
+        printf "Api not listening on $ip:$port %s[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
         exit 1
       }
       if [[ $(kubectl cluster-info | grep -q 'running') && $READY == 0 ]]; then
