finish the operator.install and improve check-kubeconfig

diff --git a/scripts/ci/check-kubeconfig b/scripts/ci/check-kubeconfig
--- a/scripts/ci/check-kubeconfig
+++ b/scripts/ci/check-kubeconfig
@@ -6,34 +6,35 @@ done
 
 export_color
 
-CONTEXT="$(kubectl config view -o jsonpath='{.current-context}')"
 
-if [[ -f $KUBECONFIG && "${CONTEXT}" != ""  ]]; then
 
-    IP="$(kubectl config view -o jsonpath="{.clusters[?(@.name=='$CONTEXT')].cluster.server}")"
-    echo ${IP#*//} | sed -e "s/:/ /" | while read ip port
-    do
-      {
-        set -e
-        nc -zvw3 $ip $port 2> /dev/null
-      } || {
-        printf "Api not listening on $ip:$port %s[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
-        exit 1
-      }
-      if kubectl cluster-info | grep -q 'running'; then
-        printf "cluster is running and ready for installing olm %s\t[ ${OK} OK ${NC} ]\n"  | expand  -t 50;
-      else
-        printf "cluster probably not running %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
-        exit 1
-      fi
+if [[ -f $KUBECONFIG  ]]; then
+    CONTEXT="$(kubectl config view -o jsonpath='{.current-context}')"
+    if [[  "${CONTEXT}" != "" ]]; then
+      IP="$(kubectl config view -o jsonpath="{.clusters[?(@.name=='$CONTEXT')].cluster.server}")"
+      echo ${IP#*//} | sed -e "s/:/ /" | while read ip port
+      do
+        {
+          set -e
+          nc -zvw3 $ip $port 2> /dev/null
+        } || {
+          printf "Api not listening on $ip:$port %s[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
+          exit 1
+        }
+        if kubectl cluster-info | grep -q 'running'; then
+          printf "cluster is running and ready for installing olm %s\t[ ${OK} OK ${NC} ]\n"  | expand  -t 50;
+        else
+          printf "cluster probably not running %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
+          exit 1
+        fi
 
-      if [[ $CONTEXT != '' ]]; then
-        printf "Find kube config %s\t[ ${OK} CONTEXT: ${CONTEXT} ${NC} ]\n"  | expand  -t 50;
-      else
-        printf "Find kube config %s\t[ ${WARN} NOT FOUND ${NC} ]\n"  | expand  -t 50; make minikube.start;
-      fi
-    done
-
+        if [[ $CONTEXT != '' ]]; then
+          printf "Find kube config %s\t[ ${OK} CONTEXT: ${CONTEXT} ${NC} ]\n"  | expand  -t 50;
+        else
+          printf "Find kube config %s\t[ ${WARN} NOT FOUND ${NC} ]\n"  | expand  -t 50; make minikube.start;
+        fi
+      done
+    fi
 else
     printf "Find kube config %s\t[ ${WARN} NOT FOUND ${NC} ]\n"  | expand  -t 50; make minikube.start;
 fi
