update operator-sdk + add CLEAN_MODE

diff --git a/scripts/ci/check-kubeconfig b/scripts/ci/check-kubeconfig
--- a/scripts/ci/check-kubeconfig
+++ b/scripts/ci/check-kubeconfig
@@ -7,6 +7,13 @@ done
 
 export_color
 
+if kubectl cluster-info | grep -q 'running'; then
+  printf "cluster is running and ready for installing olm %s\t[ ${OK} OK ${NC} ]\n"  | expand  -t 50;
+else
+  printf "cluster probably not running %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
+  exit 1
+fi
+
 if [[ -f ~/.kube/config && "$(cat ~/.kube/config  | grep -o current-context)" = "current-context"  ]]; then
     CONTEXT="$(kubectl config view -o jsonpath='{.current-context}')"
     if [[ $CONTEXT != '' ]]; then
diff --git a/scripts/ci/make-tmp b/scripts/ci/make-tmp
--- a/scripts/ci/make-tmp
+++ b/scripts/ci/make-tmp
@@ -1,19 +1,26 @@
 #!/usr/bin/env bash
 rm -rf /tmp/env.conf
 
+for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
+  . "$f"
+done
+
+export_color
+
 export PKG_FILE="$(find "$OP_PATH" -name "*.package.yaml" -print -quit)"
 export PKG_NAME="$(yq r "$PKG_FILE" "packageName")"
 
 if [[ -z "$OP_VER" || ! "$OP_VER" =~ $SEMVER_REGEX ]]; then
-  echo "Try detect operator version..."
   {
       export OP_VER="$(python3 /scripts/utils/parse-version-and-channels.py -p "$PKG_FILE" -c "$OP_CHANNEL")"
-      >&2 echo "Operator version detected $OP_VER"
+      printf "Operator version detected %s\t[ ${OK} $OP_VER ${NC} ]\n" | expand  -t 50 >&2
   } || {
-     >&2 echo "Operator version cannot be detected."perator version detected
+     >&2 echo "Operator version cannot be detected."
+    printf "Operator version cannot be detected %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
+    exit 1
   }
   if [[ -z "$OP_VER" || ! "$OP_VER" =~ $SEMVER_REGEX ]]; then
-    >&2 echo "Operator version not valid."
+    printf "Operator version not valid. %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
     exit 1
   fi
 fi
@@ -26,8 +33,9 @@ fi
 
 # Create a namespace if necessary.
 if ! kubectl get namespace "$NAMESPACE" > /dev/null 2>&1; then
-  >&2 echo "Creating namespace"
-  kubectl create namespace "$NAMESPACE"
+  printf "Creating namespace %s\t[ ${WARN} Procesing ${NC} ]\n" | expand  -t 50 >&2
+  kubectl create namespace "$NAMESPACE" > /dev/null
+  printf "Creating namespace %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 50 >&2
 fi
 
 echo -e "TMP=$(mktemp -d 2>/dev/null || mktemp -d)\nNAMESPACE=$NAMESPACE\nOP_VER=$OP_VER" > /tmp/env.conf
diff --git a/scripts/lib/cluster b/scripts/lib/cluster
--- a/scripts/lib/cluster
+++ b/scripts/lib/cluster
@@ -71,6 +71,7 @@ function check_subscription_passes() {
 function check_csv_passes() {
   local csv="$1"
   local namespace="$2"
+  local installmode="$3"
   local retries=30 # 1 minute timeout
 
   echo "Check that clusterserviceversion \"$csv\" status is set to \"Succeeded\""
@@ -87,6 +88,25 @@ function check_csv_passes() {
       fi
       echo "clusterserviceversion phase for \"$csv\": `kubectl get "clusterserviceversion/${csv}" --namespace=${namespace} -o json | jq .status.phase`"
   done
+
+  if [[ "$installmode" == "AllNamespaces" ]]; then
+      echo "Check that clusterserviceversion \"$csv\" in second namespace status is set to \"Succeeded\""
+      local retries=30
+
+      while ! [[ `kubectl get "clusterserviceversion/${csv}" --namespace=operators -o json | jq .status.phase` == \"Succeeded\" ]]; do
+          sleep 6
+          retries=$((retries - 1))
+          if [[ $retries == 0 ]]; then
+            >&2 echo "failed to reach "Succeeded" clusterserviceversion status for \"$csv\" in operators namespace"
+            # Print out CSV's 'status' section on error
+            kubectl get "clusterserviceversion/${csv}" --namespace=operators -o jsonpath="{.status}"
+            # Check operator pod(s) logs
+            get_operator_logs "$csv" "operators"
+            exit 1
+          fi
+          echo "clusterserviceversion phase for \"$csv\": `kubectl get "clusterserviceversion/${csv}" --namespace=operators -o json | jq .status.phase`"
+      done
+  fi
 
   echo "Successfully installed clusterserviceversion \"$csv\" in namespace \"$namespace\""
 }
@@ -141,7 +161,17 @@ function delete_objects_incluster() {
 
 function delete_namespace() {
     local namespace="$1"
-    kubectl delete namespace "$namespace"
+    local cleanmode="$2"
+    local OK="\033[0;32m"
+    local WARN="\033[0;33m"
+
+    if [[ "$cleanmode" == "FORCE" ]]; then
+      printf "Deleting namespace %s\t[ ${WARN} Processing ${NC} ]\n" | expand  -t 50 >&2;
+    fi
+    kubectl delete namespace "$namespace" >/dev/null
+    if [[ "$cleanmode" == "FORCE" ]]; then
+      printf "Deleting namespace %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 50 >&2
+    fi
 }
 
 function log_operator_state() {
