correctly determine kube master

diff --git a/scripts/ci/check-kubeconfig b/scripts/ci/check-kubeconfig
--- a/scripts/ci/check-kubeconfig
+++ b/scripts/ci/check-kubeconfig
@@ -9,31 +9,43 @@ export_color
 
 
 if [[ -f $KUBECONFIG  ]]; then
-    CONTEXT="$(kubectl config view -o jsonpath='{.current-context}')"
-    if [[  "${CONTEXT}" != "" ]]; then
-      IP="$(kubectl config view -o jsonpath="{.clusters[?(@.name=='$CONTEXT')].cluster.server}")"
-      echo ${IP#*//} | sed -e "s/:/ /" | while read ip port
-      do
-        {
-          set -e
-          nc -zvw3 $ip $port 2> /dev/null
-        } || {
-          printf "Api not listening on $ip:$port %s[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
-          exit 1
-        }
-        if kubectl cluster-info | grep -q 'running'; then
-          printf "cluster is running and ready for installing olm %s\t[ ${OK} OK ${NC} ]\n"  | expand  -t 50;
-        else
-          printf "cluster probably not running %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
-          exit 1
-        fi
+    printf "Find kube config %s\t[ ${OK} ${KUBECONFIG} ${NC} ]\n"  | expand  -t 50 ;
 
-        if [[ $CONTEXT != '' ]]; then
-          printf "Find kube config %s\t[ ${OK} CONTEXT: ${CONTEXT} ${NC} ]\n"  | expand  -t 50;
-        else
-          printf "Find kube config %s\t[ ${WARN} NOT FOUND ${NC} ]\n"  | expand  -t 50; make minikube.start;
-        fi
-      done
+    CURRENT_CONTEXT="$(kubectl config current-context)"
+
+    if [[  "${CURRENT_CONTEXT}" != "" ]]; then
+      printf "Find kube context %s\t[ ${OK} ${CURRENT_CONTEXT}  ${NC} ]\n"  | expand  -t 50 ;
+
+      CLUSTER="$(kubectl config view -o jsonpath="{.contexts[?(@.name=='$CURRENT_CONTEXT')].context.cluster}")"
+
+      if [[  "${CLUSTER}" != "" ]]; then
+
+        CLUSTER_URL="$(kubectl config view -o jsonpath="{.clusters[?(@.name=='$CLUSTER')].cluster.server}")"
+
+        echo ${CLUSTER_URL#*//} | sed -e "s/:/ /" | while read ip port
+        do
+          {
+            printf "Try kube master %s\t[ Trying $ip:$port ${NC} ]\n"  | expand  -t 50
+            set -e
+            nc -zvw3 $ip $port 2> /dev/null
+          } || {
+            printf "Try kube master %s\t[ ${ERR} Not responding on $ip:$port ${NC} ]\n"  | expand  -t 50 >&2
+            exit 1
+          }
+          if kubectl cluster-info | grep -q 'run
+          ning'; then
+            printf "Try kube master %s\t[ ${OK} $ip:$port ${NC} ]\n"  | expand  -t 50 ;
+          else
+            printf "Try kube master %s\t[ ${ERR} Not running on $ip:$port ${NC} ]\n"  | expand  -t 50 >&2
+            exit 1
+          fi
+        done
+
+      else
+        printf "Find kube cluster %s\t[ ${WARN} NOT FOUND ${NC} ]\n"  | expand  -t 50; make minikube.start;
+      fi
+    else
+      printf "Find kube context %s\t[ ${WARN} NOT FOUND  ${NC} ]\n"  | expand  -t 50; make minikube.start;
     fi
 else
     printf "Find kube config %s\t[ ${WARN} NOT FOUND ${NC} ]\n"  | expand  -t 50; make minikube.start;
