improve start minikube nad fix kubeconfig problem

diff --git a/scripts/ci/check-kubeconfig b/scripts/ci/check-kubeconfig
--- a/scripts/ci/check-kubeconfig
+++ b/scripts/ci/check-kubeconfig
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 
-
 for f in "$(cd "$(dirname ${BASH_SOURCE[0]})/.." && pwd)"/lib/*; do
   . "$f"
 done
 
 export_color
 
-if kubectl cluster-info | grep -q 'running'; then
-  printf "cluster is running and ready for installing olm %s\t[ ${OK} OK ${NC} ]\n"  | expand  -t 50;
-else
-  printf "cluster probably not running %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
-  exit 1
-fi
+if [[ -f $KUBECONFIG && "$(cat $KUBECONFIG  | grep -o current-context)" = "current-context"  ]]; then
 
-if [[ -f ~/.kube/config && "$(cat ~/.kube/config  | grep -o current-context)" = "current-context"  ]]; then
+    if kubectl cluster-info | grep -q 'running'; then
+      printf "cluster is running and ready for installing olm %s\t[ ${OK} OK ${NC} ]\n"  | expand  -t 50;
+    else
+      printf "cluster probably not running %s\t[ ${ERR} FAILED ${NC} ]\n" | expand  -t 50 >&2
+      exit 1
+    fi
+
     CONTEXT="$(kubectl config view -o jsonpath='{.current-context}')"
     if [[ $CONTEXT != '' ]]; then
       printf "Find kube config %s\t[ ${OK} CONTEXT: ${CONTEXT} ${NC} ]\n"  | expand  -t 50;
