fix the verify command

diff --git a/scripts/ci/env b/scripts/ci/env
--- a/scripts/ci/env
+++ b/scripts/ci/env
@@ -23,7 +23,7 @@ if [[ -z "$OP_VER" || ! "$OP_VER" =~ $SEMVER_REGEX ]]; then
       export OP_VER="$(cat $PKG_FILE | grep -Eo '\.v.*$' -m 1 | grep -Eo '[^\.v].*')"
       echo "Operator version detected $OP_VER"
   } || {
-     >&2 echo "Operator version cannot be detected."
+     >&2 echo "Operator version cannot be detected."perator version detected
   }
   if [[ -z "$OP_VER" || ! "$OP_VER" =~ $SEMVER_REGEX ]]; then
     >&2 echo "Operator version not valid."
