fix testing specific version of operator

diff --git a/scripts/ci/env b/scripts/ci/env
--- a/scripts/ci/env
+++ b/scripts/ci/env
@@ -50,10 +50,18 @@ export OP_REGISTRY_IMAGE="quay.io/operatorframework/${PKG_NAME}:${OP_VER}-regist
 export SECRET_FILE="${DEPLOY_DIR}/scorecard.secret.yaml"
 
 export CSV_FILE="$(find "$ABS_BUNDLE_PATH" -name "*${OP_VER}.clusterserviceversion.yaml" -print -quit)"
-export CSV_NAME="$(yq r "$CSV_FILE" "metadata.name")"
-export CHANNEL_NAME="$(get_channel_name "$PKG_FILE" "$CSV_NAME")"
 
-set +u
-if [[ "$REG_IMAGE" ]]; then
-  export OP_REGISTRY_IMAGE="${REG_IMAGE}"
+if [[ -f $CSV_FILE ]]; then
+
+  export CSV_NAME="$(yq r "$CSV_FILE" "metadata.name")"
+  export CHANNEL_NAME="$(python3 /scripts/lib-python/cluster/get_operator_channel.py -p "$PKG_FILE" -c "$CSV_NAME")"
+  cat "$PKG_FILE"
+  set +u
+  if [[ "$REG_IMAGE" ]]; then
+    export OP_REGISTRY_IMAGE="${REG_IMAGE}"
+  fi
+else 
+  >&2 echo "CSV file for version ${OP_VER} not found test cannot continue"
+
+  exit 1;
 fi
diff --git a/scripts/ci/make-tmp b/scripts/ci/make-tmp
--- a/scripts/ci/make-tmp
+++ b/scripts/ci/make-tmp
@@ -27,16 +27,25 @@ fi
 
 export CSV_FILE="$(find "$OP_PATH" -name "*${OP_VER}.clusterserviceversion.yaml" -print -quit)"
 
-if [[ "$NAMESPACE" == '' ]]; then
-  export NAMESPACE=$(python3 /scripts/lib-python/cluster/get-op-namespace.py -o "$PKG_NAME" -c "$CSV_FILE")
-fi
 
-# Create a namespace if necessary.
-if ! kubectl get namespace "$NAMESPACE" > /dev/null 2>&1; then
-  printf "Creating namespace %s\t[ ${WARN} Processing ${NC} ]\n" | expand  -t 50 >&2
-  kubectl create namespace "$NAMESPACE" > /dev/null
-  kubectl label namespace "$NAMESPACE" operator=test > /dev/null
-  printf "Creating namespace %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 50 >&2
-fi
+if [[ -f $CSV_FILE ]]; then
 
-echo -e "TMP=$(mktemp -d 2>/dev/null || mktemp -d)\nNAMESPACE=$NAMESPACE\nOP_VER=$OP_VER" > /tmp/env.conf
+  if [[ "$NAMESPACE" == '' ]]; then
+    export NAMESPACE=$(python3 /scripts/lib-python/cluster/get-op-namespace.py -o "$PKG_NAME" -c "$CSV_FILE")
+  fi
+
+  # Create a namespace if necessary.
+  if ! kubectl get namespace "$NAMESPACE" > /dev/null 2>&1; then
+    printf "Creating namespace %s\t[ ${WARN} Processing ${NC} ]\n" | expand  -t 50 >&2
+    kubectl create namespace "$NAMESPACE" > /dev/null
+    kubectl label namespace "$NAMESPACE" operator=test > /dev/null
+    printf "Creating namespace %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 50 >&2
+  fi
+
+  echo -e "TMP=$(mktemp -d 2>/dev/null || mktemp -d)\nNAMESPACE=$NAMESPACE\nOP_VER=$OP_VER" > /tmp/env.conf
+
+else 
+  >&2 echo "CSV file for version ${OP_VER} not found test cannot continue"
+
+  exit 1;
+fi
