refactor scorecard injection
Signed-off-by: dmesser <dmesser@redhat.com>

diff --git a/scripts/ci/install-kind b/scripts/ci/install-kind
--- a/scripts/ci/install-kind
+++ b/scripts/ci/install-kind
@@ -3,7 +3,8 @@
 set -e
 
 if [[ -z ${KIND_VER+x} ]]; then
-    KIND_VER=latest
+    echo "KIND_VER not specified, unable to choose KIND version to install"
+    exit 1
 fi
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
