Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/op-test b/scripts/ci/op-test
--- a/scripts/ci/op-test
+++ b/scripts/ci/op-test
@@ -1,4 +1,5 @@
 #!/bin/bash
+# set -e
 
 OP_TEST_SCRIPT_URL=${OP_TEST_SCRIPT_URL-"https://raw.githubusercontent.com/redhat-operator-ecosystem/operator-test-playbooks/upstream-community/test/test.sh"}
 
@@ -24,3 +25,6 @@ export OP_TEST_RESET=${OP_TEST_RESET-1}
 export OP_TEST_NOCOLOR=${OP_TEST_NOCOLOR}
 
 bash <(curl -sL $OP_TEST_SCRIPT_URL) $*
+rc=$?
+echo "rc=$rc"
+[[ $rc -eq 0 ]] || { echo "Error: rc=$rc"; exit $rc; }
