Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/scripts/ci/PR-env b/scripts/ci/PR-env
--- a/scripts/ci/PR-env
+++ b/scripts/ci/PR-env
@@ -1,10 +1,10 @@
 #!/bin/bash
-
 set -e
+
 unset OP_PATH
 unset OP_VER
 export INPUT_ENV_SCRIPT="/tmp/vars-op-path"
-export COMMUNITY_SPECIAL=''
+export COMMUNITY_SPECIAL=""
 export OP_CI_YAML_ONLY_CHANGED="false"
 
 function setName {
@@ -44,7 +44,7 @@ export OP_DEBUG=0
 # fi
 # echo "Label check done"
 
-declare -A CHANGED_FILES
+# declare -A CHANGED_FILES
 
 
 # CHANGED_FILES=$(git --no-pager log -m -1 --name-only --first-parent $OP_PR_COMMIT|awk 'NR > 6 { print }'|grep '/' 2>&1)
@@ -81,8 +81,8 @@ for sf in ${CHANGED_FILES}; do
 done
 echo
 echo
-if [ "$UPSTREAM_SET" -eq "0" ]; then
-   if [ "$COMMUNITY_SET" -eq "0" ]; then
+if [[ $UPSTREAM_SET -eq 0 ]]; then
+   if [[ $COMMUNITY_SET -eq 0 ]]; then
      echo "No operator modified, exiting, no need to test/release."; echo; echo;
 
      cat <<EOF > $INPUT_ENV_SCRIPT
@@ -95,7 +95,7 @@ fi
 
 echo
 
-[[ $OP_VER_OVERWRITE -eq 1 ]] && [[ $OP_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' cannot be set simultaneously !!!"; exit 1; }
+# [[ $OP_VER_OVERWRITE -eq 1 ]] && [[ $OP_RECREATE -eq 1 ]] && { echo "Labels 'allow/operator-version-overwrite' and 'allow/operator-recreate' cannot be set simultaneously !!!"; exit 1; }
 
 #only ci.yaml was changed:
 # CI_YML_CHECK=$(echo ${CHANGED_FILES[0]}|rev|awk -F'/' '{print $1}'|rev)
@@ -106,13 +106,16 @@ cat <<EOF > $INPUT_ENV_SCRIPT
 export OP_PATH=$OP_PATH
 export OP_NAME=$OP_NAME
 export OP_VER=$OP_VER
+export OP_PR_COMMIT=$OP_PR_COMMIT
 export STREAM_NAME=$STREAM_NAME
 export RUN_UPSTREAM=$RUN_UPSTREAM
+export OP_PR_NUMBER=$OP_PR_NUMBER
 export OP_VER_OVERWRITE=$OP_VER_OVERWRITE
 export OP_RECREATE=$OP_RECREATE
 export OP_FORCE_DEPLOY_ON_K8S=$OP_FORCE_DEPLOY_ON_K8S
 export OP_CI_YAML_ONLY_CHANGED=$OP_CI_YAML_ONLY_CHANGED
 export OP_DEBUG=$OP_DEBUG
+export COMMUNITY_SPECIAL=$COMMUNITY_SPECIAL
 EOF
 
 if [ -f $INPUT_ENV_SCRIPT ]; then
