correctly wait for scorecard to be injected

diff --git a/scripts/lib/cluster b/scripts/lib/cluster
--- a/scripts/lib/cluster
+++ b/scripts/lib/cluster
@@ -72,11 +72,11 @@ function check_csv_passes() {
   local csv="$1"
   local namespace="$2"
   local installmode="$3"
-  local retries=30 # 1 minute timeout
-
+  local retries=30 # 5 minute timeout
+  
   echo "Check that clusterserviceversion \"$csv\" status is set to \"Succeeded\""
-  while ! [[ `kubectl get "clusterserviceversion/${csv}" --namespace=${namespace} -o json | jq .status.phase` == \"Succeeded\" ]]; do
-      sleep 6
+  while ! [[ `kubectl get "clusterserviceversion/${csv}" --namespace=${namespace} -o json | jq --raw-output .status.phase` == "Succeeded" ]]; do
+      sleep 10
       retries=$((retries - 1))
       if [[ $retries == 0 ]]; then
         >&2 echo "failed to reach "Succeeded" clusterserviceversion status for \"$csv\""
@@ -93,7 +93,7 @@ function check_csv_passes() {
       echo "Check that clusterserviceversion \"$csv\" in second namespace status is set to \"Succeeded\""
       local retries=30
 
-      while ! [[ `kubectl get "clusterserviceversion/${csv}" --namespace=operators -o json | jq .status.phase` == \"Succeeded\" ]]; do
+      while ! [[ `kubectl get "clusterserviceversion/${csv}" --namespace=operators -o json | jq --raw-output .status.phase` == "Succeeded" ]]; do
           sleep 6
           retries=$((retries - 1))
           if [[ $retries == 0 ]]; then
@@ -331,10 +331,11 @@ function inject_proxy_container {
     "env": [
       {
         "name": "WATCH_NAMESPACE",
-        "valueFrom": null,
-        "fieldRef": {
-          "apiVersion": "v1",
-          "fieldPath": "metadata.namespace"
+        "valueFrom": {
+          "fieldRef": {
+            "apiVersion": "v1",
+            "fieldPath": "metadata.namespace"
+          }
         }
       }
     ],
@@ -415,8 +416,53 @@ function instrument_operator() {
   local temp_csv=$(mktemp)
   echo "$csv_json" > $temp_csv
 
-  # need to skip validation here because of downwardAPI references in scorecard proxy
   kubectl apply --validate=false -f $temp_csv
 
-  check_csv_passes $csv $namespace
+  check_scorecard_presence $csv $namespace
+}
+
+# checks whether the CSV and it's sibling Deployments hav the scorecard-proxy side car
+function check_scorecard_presence() {
+  local csv="$1"
+  local namespace="$2"
+  local retries=30 # 5 minute timeout
+  
+  echo "Check that clusterserviceversion \"$csv\" succeeded applied scorecard-proxy"
+  while [ $retries > 0 ]; do
+      sleep 10 
+
+      csv_status=$(kubectl get csv ${csv} --namespace=${namespace} -o json | jq --raw-output .status.phase) 
+      csv_scorecard_container=$(kubectl get csv ${csv} --namespace=${namespace} -o jsonpath="{$.spec.install.spec.deployments[*].spec.template.spec.containers[?(@.name=='scorecard-proxy')].command}")
+      csv_has_scorecard=$([ -z "$csv_scorecard_container" ] && echo "False" || echo "True" )
+
+      csv_deployments=$(kubectl get deployment -n $namespace -o json |  jq --raw-output ".items[] | select(.metadata.ownerReferences[].name==\"${csv}\") | .metadata.name")
+      csv_deployments_have_scorecard="True"
+
+      for deployment in $csv_deployments ; do
+          deployment_has_scorecard=$(kubectl get deployment ${deployment} --namespace=${namespace} -o jsonpath="{$.spec.template.spec.containers[?(@.name=='scorecard-proxy')].command}")
+
+          if [ -z "$deployment_has_scorecard" ] ; then 
+            csv_deployments_have_scorecard="False"
+          fi
+      done
+
+      echo "clusterserviceversion \"$csv\" is in phase: $csv_status"
+      echo "clusterserviceversion \"$csv\" has scorecard container: $csv_has_scorecard"
+      echo "clusterserviceversion \"$csv\" deployments have scorecard container: $csv_deployments_have_scorecard"
+
+      if [ "${csv_status}" == "Succeeded" ] && [ "$csv_has_scorecard" == "True" ] && [ "$csv_deployments_have_scorecard" == "True" ] ; then
+        echo "Clusterserviceversion \"$csv\" successfully applied scorecard-proxy in namespace \"$namespace\""
+        return 0;
+      else
+        retries=$((retries - 1))
+      fi
+  done
+
+  >&2 echo "failed to reach "Succeeded" phase or find scorecard in clusterserviceversion \"$csv\""
+  # Print out CSV's 'status' section on error
+  kubectl get "clusterserviceversion/${csv}" --namespace=${namespace} -o jsonpath="{.status}"
+  kubectl get csv ${csv} --namespace=${namespace} -o jsonpath="{$.spec.install.spec.deployments[*].spec.template.spec.containers[?(@.name=='scorecard-proxy')]}"
+  # Check operator pod(s) logs
+  get_operator_logs "$csv" "$namespace"
+  exit 1  
 }
