Local development tooling for operators (#685)
* update docs and small fixies

* move checking kubeconfig at first place

* fix the verify command

* add more logging and fix OP group

* fix problem with parsing yaml

* fix problem with proxy-container

* fix naming

* improve handling empty kubeconfig

* split scorecard output

* add channel option for the test operator

* add docker pull command to make file

* add configmap registy with python

* add longer time for checking csv and deployment + move configmap building to python

* add falling when some step failed

* improve handling of the kube config with empty context

* verify before installing olm if cluster is up

* fix ci travis

* small fix

* start test still in new namespace

* fix creating OP group file

* improve cleaning

* update operator-sdk + add CLEAN_MODE

* fix coloring

* fix the install olm command

* move docker file and add uninstalling OLM in force mode + check if you have installed olm

* fix old ci

* add declaration

* change olm install script

* add wait for delete items

diff --git a/scripts/lib/cluster b/scripts/lib/cluster
--- a/scripts/lib/cluster
+++ b/scripts/lib/cluster
@@ -3,13 +3,13 @@
 function wait_on_deployment() {
   local dep="$1"
   local namespace="$2"
-  local retries=20 # 2 minute timeout
+  local retries=30 # 2 minute timeout
 
   while ! kubectl rollout status -w "deployment/${dep}" --namespace=${namespace}; do
       sleep 6
       retries=$((retries - 1))
       if [[ $retries == 0 ]]; then
-        echo "FAIL: Failed to rollout deployloyment \"$dep\""
+        >&2 echo "FAIL: Failed to rollout deployloyment \"$dep\""
         exit 1
       fi
       echo "retrying check rollout status for deployment \"$dep\"..."
@@ -22,14 +22,14 @@ function check_subscription_passes() {
   local sub="$1"
   local namespace="$2"
   local packageName="$3"
-  local retries=10 # 1 minute timeout
+  local retries=30 # 1 minute timeout
 
   echo "Checking subscription \"$sub\" reaches \"AtLatestKnown\" state"
   while ! kubectl get "subscription/${sub}" --namespace=${namespace} -o json | jq .status -e &> /dev/null; do
       sleep 6
       retries=$((retries - 1))
       if [[ $retries == 0 ]]; then
-        echo "FAIL: Failed to pick up subscription \"$sub\""
+        >&2 echo "FAIL: Failed to pick up subscription \"$sub\""
         kubectl get "subscription/${sub}" --namespace=${namespace} -o yaml
         # Check if operator package is accessible on cluster, if not check the operator registry pod and exit
         if ! kubectl get packagemanifests --namespace=${namespace} | tail -n +2 | grep ${packageName} &> /dev/null; then
@@ -55,10 +55,10 @@ function check_subscription_passes() {
       sleep 6
       retries=$((retries - 1))
       if [[ $retries == 0 ]]; then
-        echo "FAIL: Failed to reach "AtLatestKnown" subscription status for \"$sub\""
+        >&2 echo "FAIL: Failed to reach "AtLatestKnown" subscription status for \"$sub\""
         kubectl get "subscription/${sub}" --namespace=${namespace} -o yaml
         installplan="`kubectl get subscription/${sub} --namespace=${namespace} -o json | jq .status.installplan.name`"
-        echo "installplan status for \"$installplan\":"
+        >&2 echo "installplan status for \"$installplan\":"
         kubectl get "installplan/${installplan}" --namespace=${namespace} -o yaml
         exit 1
       fi
@@ -71,14 +71,15 @@ function check_subscription_passes() {
 function check_csv_passes() {
   local csv="$1"
   local namespace="$2"
-  local retries=10 # 1 minute timeout
+  local installmode="$3"
+  local retries=30 # 1 minute timeout
 
   echo "Check that clusterserviceversion \"$csv\" status is set to \"Succeeded\""
   while ! [[ `kubectl get "clusterserviceversion/${csv}" --namespace=${namespace} -o json | jq .status.phase` == \"Succeeded\" ]]; do
       sleep 6
       retries=$((retries - 1))
       if [[ $retries == 0 ]]; then
-        echo "failed to reach "Succeeded" clusterserviceversion status for \"$csv\""
+        >&2 echo "failed to reach "Succeeded" clusterserviceversion status for \"$csv\""
         # Print out CSV's 'status' section on error
         kubectl get "clusterserviceversion/${csv}" --namespace=${namespace} -o jsonpath="{.status}"
         # Check operator pod(s) logs
@@ -87,6 +88,25 @@ function check_csv_passes() {
       fi
       echo "clusterserviceversion phase for \"$csv\": `kubectl get "clusterserviceversion/${csv}" --namespace=${namespace} -o json | jq .status.phase`"
   done
+
+  if [[ "$installmode" == "AllNamespaces" ]]; then
+      echo "Check that clusterserviceversion \"$csv\" in second namespace status is set to \"Succeeded\""
+      local retries=30
+
+      while ! [[ `kubectl get "clusterserviceversion/${csv}" --namespace=operators -o json | jq .status.phase` == \"Succeeded\" ]]; do
+          sleep 6
+          retries=$((retries - 1))
+          if [[ $retries == 0 ]]; then
+            >&2 echo "failed to reach "Succeeded" clusterserviceversion status for \"$csv\" in operators namespace"
+            # Print out CSV's 'status' section on error
+            kubectl get "clusterserviceversion/${csv}" --namespace=operators -o jsonpath="{.status}"
+            # Check operator pod(s) logs
+            get_operator_logs "$csv" "operators"
+            exit 1
+          fi
+          echo "clusterserviceversion phase for \"$csv\": `kubectl get "clusterserviceversion/${csv}" --namespace=operators -o json | jq .status.phase`"
+      done
+  fi
 
   echo "Successfully installed clusterserviceversion \"$csv\" in namespace \"$namespace\""
 }
@@ -135,8 +155,53 @@ function delete_objects_incluster() {
   local namespace="$2"
 
   for f in $(find "$deploy_dir" -maxdepth 1 -name "*.yaml" -print); do
-    kubectl delete --ignore-not-found=true "$(yq r "$f" "kind" | awk '{ print tolower($0) }')" "$(yq r "$f" "metadata.name")" --namespace="$namespace"
+    kubectl delete --ignore-not-found=true "$(yq r "$f" "kind" | awk '{ print tolower($0) }')" "$(yq r "$f" "metadata.name")" --namespace="$namespace" --wait=true
   done
+}
+
+function delete_namespace() {
+    local namespace="$1"
+    local cleanmode="$2"
+    local OK="\033[0;32m"
+    local WARN="\033[0;33m"
+    local NC="\033[0m"
+
+    if [[ "$cleanmode" == "FORCE" ]]; then
+      printf "Deleting namespace %s\t[ ${WARN} Processing ${NC} ]\n" | expand  -t 50 >&2;
+    fi
+    kubectl delete namespace "$namespace" >/dev/null
+    if [[ "$cleanmode" == "FORCE" ]]; then
+      printf "Deleting namespace %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 50 >&2
+    fi
+}
+
+function uninstall_olm() {
+    local OK="\033[0;32m"
+    local WARN="\033[0;33m"
+    local NC="\033[0m"
+
+
+    printf "Uninstall olm %s\t[ ${WARN} Processing ${NC} ]\n" | expand  -t 50 >&2;
+    operator-sdk alpha olm uninstall > /dev/null
+    printf "Uninstall olm %s\t[ ${OK} OK ${NC} ]\n" | expand  -t 50 >&2
+}
+
+function log_operator_state() {
+  local log_file="$1"
+  local var=$(declare -p "$2")
+  eval "declare -A objects="${var#*=}
+  local namespace="$3"
+
+  local obj_list obj
+  for k in "${!objects[@]}"; do
+    obj_list="${objects[$k]}"
+    for obj in $obj_list; do
+      >&2 echo -e "\n${k}: $(echo "$obj" | cut -d' ' -f1)\n" >> "$log_file"
+      kubectl describe "$k" $obj --namespace="$namespace" >> "$log_file" 2>&1 || true
+      >&2 echo -e "\n---\n" >> "$log_file"
+    done
+  done
+  kubectl describe pods --namespace="$namespace" >> "$log_file" 2>&1
 }
 
 function get_operator_logs() {
