Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/.github/workflows/kiwi.yaml b/.github/workflows/kiwi.yaml
--- a/.github/workflows/kiwi.yaml
+++ b/.github/workflows/kiwi.yaml
@@ -35,7 +35,7 @@ jobs:
         # run: scripts/ci/PR-traffic-light
       - name: Test aqua
         run: |
-          # scripts/ci/ansible-env
-          # source /tmp/vars-op-path
+          scripts/ci/ansible-env
+          [ -f /tmp/vars-op-path ] && source /tmp/vars-op-path || { echo "Error getting opertator variables"; exit 1; }
           # export
           echo scripts/ci/op-test kiwi $STREAM_NAME/$OP_NAME/$OP_VER
