true
Signed-off-by: J0zi <jbreza@redhat.com>

diff --git a/.github/workflows/operator_ci_installation_label.yaml b/.github/workflows/operator_ci_installation_label.yaml
--- a/.github/workflows/operator_ci_installation_label.yaml
+++ b/.github/workflows/operator_ci_installation_label.yaml
@@ -18,10 +18,10 @@ jobs:
             VALID_INSTALLATIONS=0
             echo "Labels:"
             echo "$OP_TEST_LABELS"
-            for label in $(echo $OP_TEST_LABELS); do [[ $label == installation-faile* ]] && INSTALLATION_FAILED=1; done
-            [[ $INSTALLATION_FAILED == '1' ]] && echo "::set-env name=installation-failed::$INSTALLATION_FAILED"
-            for label in $(echo $OP_TEST_LABELS); do [[ $label == installation-validate* ]] && let "VALID_INSTALLATIONS=VALID_INSTALLATIONS+1"; done
-            [[ $VALID_INSTALLATIONS == '3' ]] && echo "::set-env name=installation-is-valid::1"
+            for label in $(echo $OP_TEST_LABELS); do [[ $label == installation-faile* ]] && INSTALLATION_FAILED=1; done || true
+            [[ $INSTALLATION_FAILED == '1' ]] && echo "::set-env name=installation-failed::$INSTALLATION_FAILED" || true
+            for label in $(echo $OP_TEST_LABELS); do [[ $label == installation-validate* ]] && let "VALID_INSTALLATIONS=VALID_INSTALLATIONS+1"; done || true
+            [[ $VALID_INSTALLATIONS == '3' ]] && echo "::set-env name=installation-is-valid::1" || true
 
         - name: Add installation final label
           uses: actions/github-script@v3
