true
Signed-off-by: J0zi <jbreza@redhat.com>

diff --git a/.github/workflows/operator_ci_installation_label.yaml b/.github/workflows/operator_ci_installation_label.yaml
--- a/.github/workflows/operator_ci_installation_label.yaml
+++ b/.github/workflows/operator_ci_installation_label.yaml
@@ -16,12 +16,11 @@ jobs:
           run: |
             echo "Labels:"
             echo "$OP_TEST_LABELS"
-            for label in $(echo $OP_TEST_LABELS); do [[ $label == installation-faile* ]] && INSTALLATION_FAILED=1; done
-            [[ $INSTALLATION_FAILED == '1' ]] && echo "::set-env name=installation-failed::$INSTALLATION_FAILED"
+            for label in $(echo $OP_TEST_LABELS); do [[ $label == installation-faile* ]] && INSTALLATION_FAILED=1; done || true
+            [[ $INSTALLATION_FAILED == '1' ]] && echo "::set-env name=installation-failed::$INSTALLATION_FAILED" || true
 
         - name: Add installation final label
           uses: actions/github-script@v3
-#          needs: detect-failure
           if: ${{ env.installation-failed != '1' }}
           continue-on-error: true
           with:
