Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/.github/workflows/test_pr.yaml b/.github/workflows/test_pr.yaml
--- a/.github/workflows/test_pr.yaml
+++ b/.github/workflows/test_pr.yaml
@@ -31,7 +31,7 @@ jobs:
           # OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
         run: |
           scripts/ci/actions-env
-          [ -f /tmp/vars-op-path ] && source /tmp/vars-op-path || { echo "Error getting opertator variables"; exit 1; }
+          # [ -f /tmp/vars-op-path ] && source /tmp/vars-op-path || { echo "Error getting opertator variables"; exit 1; }
           echo "OP_TEST_CHNAGES_GITHUB=${OP_TEST_CHNAGES_GITHUB}"
           echo "::set-output name=op_test_changes_github::${OP_TEST_CHNAGES_GITHUB}"
           echo "xxx => ${{ steps.op-traffic-light.outputs.op_test_changes_github }}"
