Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/.github/workflows/test_pr.yaml b/.github/workflows/test_pr.yaml
--- a/.github/workflows/test_pr.yaml
+++ b/.github/workflows/test_pr.yaml
@@ -1,4 +1,4 @@
-name: kiwi
+name: Test pr
 
 env:
   OP_TEST_DEBUG: 1
@@ -29,5 +29,7 @@ jobs:
           OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
         run: |
           scripts/ci/actions-env
-          # [ -f /tmp/vars-op-path ] && source /tmp/vars-op-path || { echo "Error getting opertator variables"; exit 1; }
+          [ -f /tmp/vars-op-path ] && source /tmp/vars-op-path || { echo "Error getting opertator variables"; exit 1; }
+      - name: Operator test
+        run: |
           export
